### ISSUE TITLE
thread '<main>' panicked at 'index out of range',

### ISSUE THREAD

**Issue by rofrol** [dlaronson/gapbuffer#13]
When using iota i got two times 'index out of range' when I was using backspace.

```
 thread '<main>' panicked at 'index out of range', /home/user/.cargo/git/checkouts/gapbuffer-8b2fd52819acbe54/master/src/lib.rs:271
```

I can't reproduce it now

**Comment by gchp** [comment]
This was due to a problem with Iota, rather than gapbuffer.

It was fixed with this commit: https://github.com/gchp/iota/commit/d59d46b77d0e0b7d37eda792b732a5bcee8a707f
